// サイト全体の共通レイアウトを定義する場所
// pageのメタデータを定義するための型をnextより読み込んでいる
import type { Metadata } from "next";
// Geist(サンセリフ体)とGeist_Mono（等幅）という2種類のwebフォントを読み込んでいる
import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_JP } from "next/font/google";
// サイト全体に適用するグローバルなCSSファイルを読み込んでいる
import "./globals.css";

const geistSans = Geist({
  // CSS変数として定義
  variable: "--font-geist-sans",
  // フォントファイルからアルファベットや数字の部分だけをダウンロードするよう指定
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 日本語フォントの設定
const notoSansJp = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"], // ※ 日本語を使う場合は 'latin' のままでOK (日本語は自動で含まれます)
  weight: ["400", "700"], // 必要な太さを指定
  display: "swap", // フォント読み込み中の挙動
});

// headタグ内に適用させる処理
export const metadata: Metadata = {
  // ブラウザタブに表示されるサイトのタイトル部分の設定
  title: "Create Next App",
  // サイトの説明文。Googleなどの検索結果に表示されるため、変更した方が良い
  description: "Generated by create next app",
};

// サイトの骨格
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // HTML文書が英語に設定されている。日本語のサイトであれば日本語設定に変えてあげる方が良い
    <html lang="en">
      {/* classNameでサイト全体の設定を読み込んで適用している */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSansJp.variable} antialiased`}
      >
        {/* ここのchildrenでpage.tsxの内容が呼び出されてセットされる */}
        {children}
      </body>
    </html>
  );
}
